### PR TITLE
chore: update README

### LINKED ISSUE #11: Setup auto-publish workflow for index.html; deprecate README.md
Readme is outdated and does not reflect latest in index.bs.

### PR DESCRIPTION
**Pull request by marcoscaceres**
Closes #11 

The stuff in the README conflicts with the spec.

### CODE REVIEW

**Comment by yoavweiss** [comment]
Conflicts with the spec in what way?

**Comment by marcoscaceres** [comment]
See https://github.com/w3c/device-memory/issues/11 ... the README seems to predate the spec, so apparently they give conflicting information.

**Comment by yoavweiss** [comment]
I don't think that deleting the explainer is the right conclusion here. I agree that some parts of it can be refreshed, but most of it (use cases, etc) seems still relevant. Also see https://github.com/w3c/device-memory/issues/11#issuecomment-325506741

**Comment by yoavweiss** [comment]
Let's close this. If there's anything specific where the explainer and the spec conflict, file a separate issue and I'll address it.

**Pull request closed without merging**
