### PR TITLE
chore: cleanup root dir

### PR DESCRIPTION
**Pull request by marcoscaceres**
Now that this is auto-published, we don't need the .sh files. 

Additionally, some of the other files can live in the .github folder, and Github does the right thing. 🪄

### CODE REVIEW

**Comment by yoavweiss** [comment]
Thanks for cleaning up! RE the renaming to `.github/`, wouldn't that make those files less prominent for contributors?

**Comment by marcoscaceres** [comment]
>  wouldn't that make those files less prominent for contributors?

It depends. Github automatically presents the appropriate information from each when a pull request is made. 
For example, when opening an issue or pull request (in blue below):

Screen Shot 2021-06-25 at 11 51 32 am

However, it does no harm leaving them in the root, as Github will use those files to generate the above from either location (and anyone browsing the repo can spot them from the root).

In other words, your call :)

**Comment by yoavweiss** [comment]
Let's leave them at the root then, as it seems more discoverable.

**Comment by marcoscaceres** [comment]
Sounds good. Closing.

**Pull request closed without merging**
